import {
  createContext, useContext, useEffect, useMemo, useState
} from "react";
import { supabase } from "../lib/supabase";

const AppContext = createContext();

const text = {
  en: {
    home:"Home", profile:"Profile", language:"Language",
    settings:"Settings", logout:"Logout", login:"Login",
    register:"Register", welcome:"Welcome", dashboard:"Dashboard",
    training:"Training", assessment:"Assessment",
    certificates:"Certificates", history:"History",
    start:"Start Training", verify:"Verify Certificate",
    offline:"Offline Ready", light:"Light", dark:"Dark",
    workers:"Workers", questions:"Questions",
    compliance:"Compliance", modules:"Training Modules", certificate:"Certificate", user:"User",
    getStarted:"Get Started", safetyEyebrow:"Smart Industrial Safety Training",
    heroTitle:"Safety training that workers can",
    heroTitleAccent:"see, practise and remember.",
    heroDescription:"SurakshaSetu brings interactive safety training, camera-based practical scenarios, assessments and verifiable certification to mining and manufacturing workers across Jharkhand.",
    android:"Android 10+", noHeadset:"No headset", industrialSafety:"Industrial Safety",
    fireSafety:"Fire Safety", gasSafety:"Gas Safety", machinery:"Machinery",
    electrical:"Electrical", safetyReadiness:"Safety readiness",
    safetyDomains:"Safety domains", languages:"Languages", cameraTraining:"Camera training",
    verifiedCertificates:"Verified certificates", trainingEcosystem:"Training ecosystem",
    platformJourney:"One platform, complete safety journey",
    journeyDescription:"Learn concepts, practise scenarios, prove understanding and carry a verifiable safety record.",
    interactiveTraining:"Interactive AR Training",
    interactiveTrainingDesc:"Camera-led hazard recognition and interactive safety scenarios without an external headset.",
    lowConnectivity:"Low-connectivity Ready",
    lowConnectivityDesc:"Optimised training assets and PWA caching for field environments with unreliable internet.",
    regionalLanguages:"Regional Language Access",
    regionalLanguagesDesc:"English, Hindi and Santali content for a more accessible worker experience.",
    qrCertification:"QR Certification",
    qrCertificationDesc:"Unique certificate records connected to a public verification flow.",
    adminCompliance:"Admin Compliance",
    adminComplianceDesc:"Worker, assessment, certification and completion information in one dashboard.",
    mobileFirst:"Mobile First",
    mobileFirstDesc:"Responsive interface designed around affordable Android smartphones.",
    practicalTraining:"Practical training for critical hazards", howItWorks:"How it works",
    verifiedJourney:"From learning to verified certification", learn:"Learn",
    learnDesc:"Study visual safety content", practise:"Practise",
    practiseDesc:"Complete interactive scenarios", assess:"Assess",
    assessDesc:"Answer module assessments", certify:"Certify",
    certifyDesc:"Receive a QR-verifiable record", saferWorkforce:"Build a safer, better-prepared workforce.",
    connectedPlatform:"Training, assessment and compliance connected through one simple platform.",
    accessSurakshaSetu:"Access SurakshaSetu", industrialLearning:"Industrial safety learning for Jharkhand's workforce.",
    developedBy:"Developed by", problemStatement:"SIH Problem Statement 26041",
    journeyLearn:"Study visual safety content", journeyPractise:"Complete interactive scenarios",
    journeyAssess:"Answer module assessments", journeyCertify:"Receive a QR-verifiable record",
    backToHome:"Back to home", welcomeBack:"Welcome back", createAccount:"Create your account",
    signInContinue:"Sign in securely to continue.",
    chooseRole:"Choose your role and enter your identity details.",
    worker:"Worker", administrator:"Administrator", fullName:"Full name",
    workerId:"Worker ID", adminId:"Admin ID", sector:"Sector", mining:"Mining",
    steel:"Steel", manufacturing:"Manufacturing", micaProcessing:"Mica Processing",
    contractWork:"Contract Work", other:"Other", email:"Email", password:"Password",
    pleaseWait:"Please wait...", newToApp:"New to SurakshaSetu?",
    alreadyRegistered:"Already registered?", backendNotConfigured:"Backend is not configured. Add Supabase values to .env first.",
    accountCouldNotBeCreated:"Could not create account.", confirmEmailToLogin:"Account created. Confirm your email, then login.",
    englishQuestionRequired:"English question is required.",
    selectedAnswerRequired:"The selected correct answer cannot be empty.", authEyebrow:"Industrial safety starts with preparation.",
    questionTranslationRequired:"Enter the question in English, Hindi, and Santali before saving.",
    optionsTranslationRequired:"Translate each filled answer option and any explanation into Hindi and Santali.",
    authDescription:"Access training, practical simulations, assessments and verifiable safety credentials.",
    backToDashboard:"Back to dashboard", workerCentre:"Worker Safety Centre", module:"Module", verificationQr:"Verification QR",
    average:"Average", performance:"Performance", assessmentHistory:"Assessment History",
    noCompletedAssessments:"No completed assessments yet.",
    openModule:"Open Module", viewResult:"View result", removeFromHistory:"Remove from history",
    verifiedRecords:"Verified records", completeForCertificate:"Complete an eligible assessment to earn a certificate.",
    viewCertificate:"View certificate", verified:"Verified", dashboardBack:"Dashboard",
    safetyModule:"Safety training module", understand:"Understand", learningObjectives:"Learning objectives",
    safetyPrinciple:"Safety principle", remember:"Remember", safetyPrincipleText:"Stop and assess the hazard before acting. Follow site procedures, warning signs, authorised isolation, required PPE and emergency instructions. Never enter a hazardous area merely to complete a training activity.", practical:"Interactive Practical",
    cameraExercise:"Camera-assisted hazard exercise", startAssessment:"Start Assessment",
    completeModuleTest:"Complete the module test",
    completeAllQuestions:"Complete all questions before submitting.",
    assessmentSwitchWarning:"Switching tabs or apps while the assessment is active will invalidate this attempt. It will not be submitted.",
    noQuestionsConfigured:"No questions are currently configured for this module.",
    translationsIncomplete:"This assessment is unavailable because one or more questions are missing English, Hindi, or Santali translations. Contact an administrator.",
    translationUnavailable:"Translation unavailable",
    attemptInterrupted:"Attempt interrupted", attemptNotSubmitted:"This attempt was not submitted. Start the assessment again.",
    restartAssessment:"Restart Assessment", activeAssessment:"Active assessment", question:"Question",
    answered:"Answered", of:"of", submitting:"Submitting...", submitAssessment:"Submit Assessment",
    assessmentResult:"Assessment result", assessmentCompleted:"Assessment completed",
    reviewAndRetry:"Review the module and try again", generateCertificate:"Generate Certificate",
    answerReview:"Answer review", correctAnswers:"Correct answers", yourAnswer:"Your answer:",
    correctAnswer:"Correct answer:", correct:"Correct", incorrect:"Incorrect",
    certificateReady:"Certificate ready", generating:"Generating...", congratulations:"Congratulations",
    certificateOfCompletion:"Certificate of Completion", awardedTo:"This certificate is proudly awarded to",
    score:"Score", certificateId:"Certificate ID", issued:"Issued", scanToVerify:"Scan QR to verify this certificate online.",
    downloadPdf:"Download PDF", certificateVerification:"Certificate Verification",
    enterCertificateId:"Enter the unique SurakshaSetu Certificate ID.", checking:"Checking...",
    verifyAction:"Verify", certificateVerified:"Certificate Verified", authenticRecord:"Authentic SurakshaSetu record",
    certificateRevoked:"This certificate has been revoked and is no longer valid.", certificateNotFound:"Certificate not found.",
    workerManagement:"Worker Management", registeredWorkerDesc:"View registered workers and manage account status.",
    manageModuleDescription:"Manage assessment content associated with each safety domain.",
    searchWorker:"Search name, Worker ID or sector...", name:"Name", status:"Status", joined:"Joined", actions:"Actions",
    active:"Active", inactive:"Inactive", activate:"Activate", deactivate:"Deactivate", remove:"Remove",
    noWorkersFound:"No workers found.", moduleNotFound:"Module not found.",
    questionsFound:"No questions found.", noAssessments:"No assessment records.", noCertificates:"No matching certificate found.",
    removeAssessmentConfirm:"Remove this assessment from your history?", removeCertificateConfirm:"Remove this certificate from your history? The original verification record will remain valid.",
    couldNotRemoveAssessment:"Could not remove assessment:", couldNotRemoveCertificate:"Could not remove certificate:",
    workforce:"Workforce", trainingContent:"Training content", assessmentEngine:"Assessment engine",
    addQuestion:"Add Question", editQuestion:"Edit Question", questionEditor:"Question editor", questionManager:"Question Manager", questionManagerDescription:"Create, edit and delete multilingual assessment questions.",
    manageQuestions:"Manage Questions", searchQuestions:"Search questions...", allModules:"All modules",
    questionType:"Question Type", sortOrder:"Sort Order", imageOptional:"Image URL (optional)",
    explanation:"Explanation", delete:"Delete", save:"Save", modulePerformance:"Module performance",
    originalCertificateRecord:"Original issued certificate record.", completed:"Completed", moduleAssessments:"Module-wise assessments", complianceDescription:"Platform-wide training and certification performance.",
    totalWorkers:"Total Workers", averageScore:"Average Score", safetyCompliance:"Safety Compliance Overview",
    issuedCertificates:"Certificate Centre", searchCertificates:"Search Worker Name / Worker ID / Certificate ID...",
    certificateCount:"certificates found", oneCertificateFound:"certificate found", revoked:"Revoked", revoke:"Revoke", view:"View",
    assessmentRecords:"Assessment Records", workerHistoryAdminNote:"Removing a worker-side history item does not remove this compliance record.", liveActivity:"Live activity", recentAssessments:"Recent Assessments",
    noAssessmentsYet:"No assessments yet.", date:"Date", percentage:"Percentage", submitted:"Submitted",
    questionDeleteConfirm:"Delete this question?", assessmentDeleteConfirm:"Remove this assessment from Admin records?",
    certificateRevokeConfirm:"Revoke this certificate?", workerRemoveConfirm:"Remove this worker from Admin worker list? Assessment and certificate records will remain available."
  },
  hi: {
    home:"होम", profile:"प्रोफ़ाइल", language:"भाषा",
    settings:"सेटिंग्स", logout:"लॉगआउट", login:"लॉगिन",
    register:"पंजीकरण", welcome:"स्वागत है", dashboard:"डैशबोर्ड",
    training:"प्रशिक्षण", assessment:"मूल्यांकन",
    certificates:"प्रमाणपत्र", history:"इतिहास",
    start:"प्रशिक्षण शुरू करें", verify:"प्रमाणपत्र सत्यापित करें",
    offline:"ऑफलाइन उपलब्ध", light:"लाइट", dark:"डार्क",
    workers:"कर्मचारी", questions:"प्रश्न",
    compliance:"अनुपालन", modules:"प्रशिक्षण मॉड्यूल", certificate:"प्रमाणपत्र", user:"उपयोगकर्ता",
    getStarted:"शुरू करें", safetyEyebrow:"स्मार्ट औद्योगिक सुरक्षा प्रशिक्षण",
    heroTitle:"ऐसा सुरक्षा प्रशिक्षण जिसे कर्मचारी",
    heroTitleAccent:"देखें, अभ्यास करें और याद रखें।",
    heroDescription:"सुरक्षासेतु झारखंड के खनन और विनिर्माण कर्मचारियों के लिए इंटरैक्टिव सुरक्षा प्रशिक्षण, कैमरा-आधारित व्यावहारिक परिदृश्य, मूल्यांकन और सत्यापन योग्य प्रमाणन उपलब्ध कराता है।",
    android:"Android 10+", noHeadset:"हेडसेट की आवश्यकता नहीं", industrialSafety:"औद्योगिक सुरक्षा",
    fireSafety:"अग्नि सुरक्षा", gasSafety:"गैस सुरक्षा", machinery:"मशीनरी",
    electrical:"विद्युत सुरक्षा", safetyReadiness:"सुरक्षा तैयारी",
    safetyDomains:"सुरक्षा क्षेत्र", languages:"भाषाएँ", cameraTraining:"कैमरा प्रशिक्षण",
    verifiedCertificates:"सत्यापित प्रमाणपत्र", trainingEcosystem:"प्रशिक्षण व्यवस्था",
    platformJourney:"एक मंच, सुरक्षा की पूरी यात्रा",
    journeyDescription:"अवधारणाएँ सीखें, परिदृश्यों का अभ्यास करें, समझ साबित करें और सत्यापन योग्य सुरक्षा रिकॉर्ड प्राप्त करें।",
    interactiveTraining:"इंटरैक्टिव AR प्रशिक्षण",
    interactiveTrainingDesc:"बाहरी हेडसेट के बिना कैमरे से खतरे पहचानें और इंटरैक्टिव सुरक्षा परिदृश्यों का अभ्यास करें।",
    lowConnectivity:"कम कनेक्टिविटी में उपलब्ध",
    lowConnectivityDesc:"कमजोर इंटरनेट वाले कार्यस्थलों के लिए अनुकूलित प्रशिक्षण सामग्री और PWA कैशिंग।",
    regionalLanguages:"क्षेत्रीय भाषाओं में सुविधा",
    regionalLanguagesDesc:"कर्मचारियों के लिए अधिक सुलभ अनुभव हेतु अंग्रेज़ी, हिंदी और संताली सामग्री।",
    qrCertification:"QR प्रमाणन",
    qrCertificationDesc:"सार्वजनिक सत्यापन सुविधा से जुड़े विशिष्ट प्रमाणपत्र रिकॉर्ड।",
    adminCompliance:"प्रशासनिक अनुपालन",
    adminComplianceDesc:"एक डैशबोर्ड में कर्मचारी, मूल्यांकन, प्रमाणन और पूर्णता की जानकारी।",
    mobileFirst:"मोबाइल प्राथमिकता",
    mobileFirstDesc:"किफायती Android स्मार्टफ़ोन के लिए बनाया गया अनुकूल इंटरफ़ेस।",
    practicalTraining:"महत्वपूर्ण खतरों के लिए व्यावहारिक प्रशिक्षण", howItWorks:"यह कैसे काम करता है",
    verifiedJourney:"सीखने से सत्यापित प्रमाणन तक", learn:"सीखें",
    learnDesc:"दृश्य सुरक्षा सामग्री पढ़ें", practise:"अभ्यास करें",
    practiseDesc:"इंटरैक्टिव परिदृश्य पूरे करें", assess:"मूल्यांकन दें",
    assessDesc:"मॉड्यूल के मूल्यांकन प्रश्नों के उत्तर दें", certify:"प्रमाणित हों",
    certifyDesc:"QR से सत्यापित होने वाला रिकॉर्ड पाएँ", saferWorkforce:"अधिक सुरक्षित और बेहतर तैयार कार्यबल बनाएँ।",
    connectedPlatform:"प्रशिक्षण, मूल्यांकन और अनुपालन एक सरल मंच पर जुड़े हुए हैं।",
    accessSurakshaSetu:"सुरक्षासेतु का उपयोग करें", industrialLearning:"झारखंड के कार्यबल के लिए औद्योगिक सुरक्षा प्रशिक्षण।",
    developedBy:"निर्माता", problemStatement:"SIH समस्या विवरण 26041",
    journeyLearn:"दृश्य सुरक्षा सामग्री पढ़ें", journeyPractise:"इंटरैक्टिव परिदृश्य पूरे करें",
    journeyAssess:"मॉड्यूल के मूल्यांकन प्रश्नों के उत्तर दें", journeyCertify:"QR से सत्यापित होने वाला रिकॉर्ड पाएँ",
    backToHome:"होम पर वापस जाएँ", welcomeBack:"वापसी पर स्वागत है", createAccount:"अपना खाता बनाएँ",
    signInContinue:"जारी रखने के लिए सुरक्षित रूप से लॉगिन करें।",
    chooseRole:"अपनी भूमिका चुनें और पहचान संबंधी विवरण भरें।",
    worker:"कर्मचारी", administrator:"प्रशासक", fullName:"पूरा नाम",
    workerId:"कर्मचारी आईडी", adminId:"एडमिन आईडी", sector:"क्षेत्र", mining:"खनन",
    steel:"इस्पात", manufacturing:"विनिर्माण", micaProcessing:"अभ्रक प्रसंस्करण",
    contractWork:"ठेका कार्य", other:"अन्य", email:"ईमेल", password:"पासवर्ड",
    pleaseWait:"कृपया प्रतीक्षा करें...", newToApp:"सुरक्षासेतु पर नए हैं?",
    alreadyRegistered:"पहले से पंजीकृत हैं?", backendNotConfigured:"बैकएंड कॉन्फ़िगर नहीं है। पहले .env में Supabase मान जोड़ें।",
    accountCouldNotBeCreated:"खाता नहीं बनाया जा सका।", confirmEmailToLogin:"खाता बन गया है। ईमेल की पुष्टि करें, फिर लॉगिन करें।",
    englishQuestionRequired:"अंग्रेज़ी में प्रश्न देना आवश्यक है।",
    selectedAnswerRequired:"चुना गया सही उत्तर खाली नहीं हो सकता।", authEyebrow:"औद्योगिक सुरक्षा की शुरुआत तैयारी से होती है।",
    questionTranslationRequired:"सहेजने से पहले प्रश्न अंग्रेज़ी, हिंदी और संताली तीनों में भरें।",
    optionsTranslationRequired:"हर भरे हुए उत्तर विकल्प और व्याख्या का हिंदी तथा संताली अनुवाद करें।",
    authDescription:"प्रशिक्षण, व्यावहारिक अभ्यास, मूल्यांकन और सत्यापन योग्य सुरक्षा प्रमाणपत्र पाएँ।",
    backToDashboard:"डैशबोर्ड पर वापस जाएँ", workerCentre:"कर्मचारी सुरक्षा केंद्र", module:"मॉड्यूल", verificationQr:"सत्यापन QR",
    average:"औसत", performance:"प्रदर्शन", assessmentHistory:"मूल्यांकन इतिहास",
    noCompletedAssessments:"अभी तक कोई मूल्यांकन पूरा नहीं हुआ है।",
    openModule:"मॉड्यूल खोलें", viewResult:"परिणाम देखें", removeFromHistory:"इतिहास से हटाएँ",
    verifiedRecords:"सत्यापित रिकॉर्ड", completeForCertificate:"प्रमाणपत्र पाने के लिए पात्र मूल्यांकन पूरा करें।",
    viewCertificate:"प्रमाणपत्र देखें", verified:"सत्यापित", dashboardBack:"डैशबोर्ड",
    safetyModule:"सुरक्षा प्रशिक्षण मॉड्यूल", understand:"समझें", learningObjectives:"सीखने के उद्देश्य",
    safetyPrinciple:"सुरक्षा सिद्धांत", remember:"याद रखें", practical:"इंटरैक्टिव व्यावहारिक अभ्यास",
    cameraExercise:"कैमरे से खतरे पहचानने का अभ्यास", startAssessment:"मूल्यांकन शुरू करें",
    completeModuleTest:"मॉड्यूल की परीक्षा पूरी करें",
    completeAllQuestions:"जमा करने से पहले सभी प्रश्नों के उत्तर दें।",
    assessmentSwitchWarning:"मूल्यांकन के दौरान टैब या ऐप बदलने पर यह प्रयास अमान्य हो जाएगा और जमा नहीं होगा।",
    noQuestionsConfigured:"इस मॉड्यूल के लिए अभी कोई प्रश्न उपलब्ध नहीं है।",
    translationsIncomplete:"यह मूल्यांकन उपलब्ध नहीं है क्योंकि एक या अधिक प्रश्नों का अंग्रेज़ी, हिंदी या संताली अनुवाद अधूरा है। व्यवस्थापक से संपर्क करें।",
    translationUnavailable:"अनुवाद उपलब्ध नहीं है",
    attemptInterrupted:"प्रयास बाधित हुआ", attemptNotSubmitted:"यह प्रयास जमा नहीं हुआ। मूल्यांकन फिर से शुरू करें।",
    restartAssessment:"मूल्यांकन फिर शुरू करें", activeAssessment:"चालू मूल्यांकन", question:"प्रश्न",
    answered:"उत्तर दिए", of:"में से", submitting:"जमा हो रहा है...", submitAssessment:"मूल्यांकन जमा करें",
    assessmentResult:"मूल्यांकन परिणाम", assessmentCompleted:"मूल्यांकन पूरा हुआ",
    reviewAndRetry:"मॉड्यूल दोहराएँ और फिर प्रयास करें", generateCertificate:"प्रमाणपत्र बनाएँ",
    answerReview:"उत्तर समीक्षा", correctAnswers:"सही उत्तर", yourAnswer:"आपका उत्तर:",
    correctAnswer:"सही उत्तर:", correct:"सही", incorrect:"गलत",
    certificateReady:"प्रमाणपत्र तैयार है", generating:"बनाया जा रहा है...", congratulations:"बधाई हो",
    certificateOfCompletion:"पूर्णता प्रमाणपत्र", awardedTo:"यह प्रमाणपत्र गर्व से प्रदान किया जाता है",
    score:"स्कोर", certificateId:"प्रमाणपत्र आईडी", issued:"जारी किया गया", scanToVerify:"इस प्रमाणपत्र को ऑनलाइन सत्यापित करने के लिए QR स्कैन करें।",
    downloadPdf:"PDF डाउनलोड करें", certificateVerification:"प्रमाणपत्र सत्यापन",
    enterCertificateId:"विशिष्ट सुरक्षासेतु प्रमाणपत्र आईडी दर्ज करें।", checking:"जाँच हो रही है...",
    verifyAction:"सत्यापित करें", certificateVerified:"प्रमाणपत्र सत्यापित",
    authenticRecord:"प्रामाणिक सुरक्षासेतु रिकॉर्ड", certificateRevoked:"यह प्रमाणपत्र रद्द कर दिया गया है और अब मान्य नहीं है।",
    certificateNotFound:"प्रमाणपत्र नहीं मिला।", workerManagement:"कर्मचारी प्रबंधन",
    registeredWorkerDesc:"पंजीकृत कर्मचारियों और खाते की स्थिति देखें और प्रबंधित करें।",
    searchWorker:"नाम, कर्मचारी आईडी या क्षेत्र खोजें...", name:"नाम", status:"स्थिति", joined:"शामिल हुए", actions:"कार्रवाई",
    active:"सक्रिय", inactive:"निष्क्रिय", activate:"सक्रिय करें", deactivate:"निष्क्रिय करें", remove:"हटाएँ",
    noWorkersFound:"कोई कर्मचारी नहीं मिला।", moduleNotFound:"मॉड्यूल नहीं मिला।",
    questionsFound:"कोई प्रश्न नहीं मिला।", noAssessments:"मूल्यांकन रिकॉर्ड उपलब्ध नहीं हैं।", noCertificates:"मिलता-जुलता प्रमाणपत्र नहीं मिला।",
    removeAssessmentConfirm:"इस मूल्यांकन को अपने इतिहास से हटाएँ?", removeCertificateConfirm:"इस प्रमाणपत्र को अपने इतिहास से हटाएँ? मूल सत्यापन रिकॉर्ड मान्य रहेगा।",
    couldNotRemoveAssessment:"मूल्यांकन नहीं हटाया जा सका:", couldNotRemoveCertificate:"प्रमाणपत्र नहीं हटाया जा सका:",
    safetyPrincipleText:"कार्रवाई से पहले रुकें और खतरे का आकलन करें। साइट की प्रक्रिया, चेतावनी संकेत, अधिकृत आइसोलेशन, आवश्यक PPE और आपातकालीन निर्देशों का पालन करें। केवल प्रशिक्षण पूरा करने के लिए कभी भी खतरनाक क्षेत्र में प्रवेश न करें।",
    workforce:"कार्यबल", trainingContent:"प्रशिक्षण सामग्री", manageModuleDescription:"हर सुरक्षा क्षेत्र से जुड़ी मूल्यांकन सामग्री प्रबंधित करें।", assessmentEngine:"मूल्यांकन प्रणाली",
    addQuestion:"प्रश्न जोड़ें", editQuestion:"प्रश्न संपादित करें", questionEditor:"प्रश्न संपादक", questionManager:"प्रश्न प्रबंधक", questionManagerDescription:"बहुभाषी मूल्यांकन प्रश्न बनाएँ, संपादित करें और हटाएँ।",
    manageQuestions:"प्रश्न प्रबंधित करें", searchQuestions:"प्रश्न खोजें...", allModules:"सभी मॉड्यूल",
    questionType:"प्रश्न का प्रकार", sortOrder:"क्रम", imageOptional:"छवि URL (वैकल्पिक)",
    explanation:"व्याख्या", delete:"हटाएँ", save:"सहेजें", modulePerformance:"मॉड्यूल प्रदर्शन",
    originalCertificateRecord:"मूल जारी प्रमाणपत्र रिकॉर्ड।", completed:"पूरा हुआ", moduleAssessments:"मॉड्यूल के अनुसार मूल्यांकन", complianceDescription:"पूरे मंच का प्रशिक्षण और प्रमाणन प्रदर्शन।",
    totalWorkers:"कुल कर्मचारी", averageScore:"औसत स्कोर", safetyCompliance:"सुरक्षा अनुपालन सारांश",
    issuedCertificates:"प्रमाणपत्र केंद्र", searchCertificates:"कर्मचारी नाम / आईडी / प्रमाणपत्र आईडी खोजें...",
    certificateCount:"प्रमाणपत्र मिले", oneCertificateFound:"प्रमाणपत्र मिला", revoked:"रद्द", revoke:"रद्द करें", view:"देखें",
    assessmentRecords:"मूल्यांकन रिकॉर्ड", workerHistoryAdminNote:"कर्मचारी की हिस्ट्री से हटाने पर यह अनुपालन रिकॉर्ड नहीं हटता।", liveActivity:"लाइव गतिविधि", recentAssessments:"हाल के मूल्यांकन",
    noAssessmentsYet:"अभी तक कोई मूल्यांकन नहीं।", date:"तारीख", percentage:"प्रतिशत", submitted:"जमा किया गया",
    questionDeleteConfirm:"यह प्रश्न हटाएँ?", assessmentDeleteConfirm:"इस मूल्यांकन को एडमिन रिकॉर्ड से हटाएँ?",
    certificateRevokeConfirm:"यह प्रमाणपत्र रद्द करें?", workerRemoveConfirm:"इस कर्मचारी को एडमिन सूची से हटाएँ? मूल्यांकन और प्रमाणपत्र रिकॉर्ड उपलब्ध रहेंगे।"
  },
  sat: {
    home:"ᱚᱲᱟᱜ", profile:"ᱯᱨᱚᱯᱷᱟᱭᱤᱞ", language:"ᱯᱟᱹᱨᱥᱤ",
    settings:"ᱥᱮᱴᱤᱝ", logout:"ᱞᱚᱜ ᱟᱣᱩᱴ", login:"ᱞᱚᱜᱤᱱ",
    register:"ᱨᱮᱡᱤᱥᱴᱟᱨ", welcome:"ᱡᱚᱦᱟᱨ", dashboard:"ᱰᱮᱥᱵᱳᱨᱰ",
    training:"ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ", assessment:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ",
    certificates:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ", history:"ᱦᱤᱥᱴᱨᱤ",
    start:"ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ ᱮᱦᱚᱵ",
    verify:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱧᱮᱞ",
    offline:"ᱚᱯᱷᱞᱟᱭᱤᱱ", light:"ᱞᱟᱭᱤᱴ", dark:"ᱰᱟᱨᱠ",
    workers:"ᱠᱟᱹᱢᱤᱭᱟᱹ", questions:"ᱠᱩᱠᱞᱤ",
    compliance:"ᱠᱚᱢᱯᱞᱟᱭᱮᱱᱥ", modules:"ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ ᱢᱚᱰᱭᱩᱞ", certificate:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ", user:"ᱵᱮᱵᱚᱦᱟᱨᱤᱡ",
    getStarted:"ᱮᱦᱚᱵ ᱢᱮ", safetyEyebrow:"ᱥᱢᱟᱨᱴ ᱤᱱᱰᱟᱥᱴᱨᱤᱭᱟᱞ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ",
    heroTitle:"ᱥᱩᱨᱚᱠᱪᱷᱟ ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ ᱡᱟᱦᱟᱸ ᱠᱟᱹᱢᱤᱭᱟᱹᱠᱚ",
    heroTitleAccent:"ᱧᱮᱞ, ᱥᱤᱠᱷᱟᱹ ᱟᱨ ᱦᱚᱲᱢᱚᱜ ᱫᱟᱲᱮᱭᱟ᱾",
    heroDescription:"ᱥᱩᱨᱚᱠᱪᱷᱟᱥᱮᱛᱩ ᱡᱷᱟᱲᱠᱷᱚᱱᱰ ᱨᱮᱭᱟᱜ ᱢᱟᱭᱤᱱᱤᱝ ᱟᱨ ᱢᱮᱱᱩᱯᱷᱮᱠᱪᱟᱨᱤᱝ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ ᱞᱟᱹᱜᱤᱫ ᱤᱱᱴᱟᱨᱮᱠᱴᱤᱵ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱥᱤᱠᱷᱟᱹ, ᱠᱮᱢᱨᱟ ᱥᱟᱶ ᱠᱟᱹᱢᱤ ᱥᱤᱠᱷᱟᱹ, ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱟᱨ ᱵᱤᱥᱣᱟᱥᱡᱚᱜ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱥᱚᱱ ᱮᱢᱟᱭᱟ᱾",
    android:"Android 10+", noHeadset:"ᱦᱮᱰᱥᱮᱴ ᱵᱟᱝ ᱞᱟᱹᱠᱛᱤ", industrialSafety:"ᱤᱱᱰᱟᱥᱴᱨᱤᱭᱟᱞ ᱥᱩᱨᱚᱠᱪᱷᱟ",
    fireSafety:"ᱥᱮᱸᱜᱮᱞ ᱥᱩᱨᱚᱠᱪᱷᱟ", gasSafety:"ᱜᱮᱥ ᱥᱩᱨᱚᱠᱪᱷᱟ", machinery:"ᱢᱮᱥᱤᱱᱟᱨᱤ",
    electrical:"ᱵᱤᱡᱽᱞᱤ", safetyReadiness:"ᱥᱩᱨᱚᱠᱪᱷᱟ ᱛᱮᱭᱟᱨᱤ",
    safetyDomains:"ᱥᱩᱨᱚᱠᱪᱷᱟ ᱵᱤᱥᱚᱭ", languages:"ᱯᱟᱹᱨᱥᱤ", cameraTraining:"ᱠᱮᱢᱨᱟ ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ",
    verifiedCertificates:"ᱵᱤᱥᱣᱟᱥᱡᱚᱜ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ", trainingEcosystem:"ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ ᱵᱮᱵᱚᱥᱛᱷᱟ",
    platformJourney:"ᱢᱤᱫ ᱯᱞᱮᱴᱯᱷᱚᱨᱢ, ᱯᱩᱨᱟᱹ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱡᱚᱱᱚᱢ",
    journeyDescription:"ᱵᱤᱥᱚᱭ ᱥᱤᱠᱷᱟᱹ, ᱥᱤᱠᱟᱹᱣ ᱠᱚ ᱥᱤᱠᱷᱟᱹ, ᱵᱩᱡᱷᱟᱹᱣ ᱯᱨᱚᱢᱟᱬ ᱢᱮ ᱟᱨ ᱵᱤᱥᱣᱟᱥᱡᱚᱜ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱨᱮᱠᱚᱨᱰ ᱦᱚᱪᱚ ᱢᱮ᱾",
    interactiveTraining:"ᱤᱱᱴᱟᱨᱮᱠᱴᱤᱵ AR ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ",
    interactiveTrainingDesc:"ᱵᱟᱦᱨᱮᱭᱟᱜ ᱦᱮᱰᱥᱮᱴ ᱵᱮᱜᱚᱨ ᱠᱮᱢᱨᱟ ᱥᱟᱶ ᱦᱟᱡᱟᱨᱰ ᱵᱟᱰᱟᱭ ᱟᱨ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱥᱤᱠᱟᱹᱣ ᱢᱮ᱾",
    lowConnectivity:"ᱠᱚᱢ ᱤᱱᱴᱟᱨᱱᱮᱴ ᱨᱮ ᱦᱚᱸ ᱠᱟᱹᱢᱤᱭᱟᱹ",
    lowConnectivityDesc:"ᱠᱚᱢᱡᱚᱨ ᱤᱱᱴᱟᱨᱱᱮᱴ ᱴᱷᱟᱶ ᱞᱟᱹᱜᱤᱫ ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ ᱟᱨ PWA ᱠᱮᱥᱤᱝ᱾",
    regionalLanguages:"ᱟᱹᱯᱱᱟᱹᱨ ᱯᱟᱹᱨᱥᱤ ᱥᱮᱵᱟ",
    regionalLanguagesDesc:"ᱠᱟᱹᱢᱤᱭᱟᱹᱠᱚ ᱞᱟᱹᱜᱤᱫ English, Hindi ᱟᱨ Santali ᱨᱮ ᱥᱟᱢᱟᱜᱨᱤ᱾",
    qrCertification:"QR ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱥᱚᱱ",
    qrCertificationDesc:"ᱥᱟᱨᱵᱚᱡᱚᱱᱤᱠ ᱵᱤᱥᱣᱟᱥ ᱥᱮᱵᱟ ᱥᱟᱶ ᱡᱩᱲᱟᱹᱣ ᱠᱟᱱ ᱵᱤᱥᱮᱥ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱨᱮᱠᱚᱨᱰ᱾",
    adminCompliance:"ᱮᱰᱢᱤᱱ ᱠᱚᱢᱯᱞᱟᱭᱮᱱᱥ",
    adminComplianceDesc:"ᱢᱤᱫ ᱰᱮᱥᱵᱳᱨᱰ ᱨᱮ ᱠᱟᱹᱢᱤᱭᱟᱹ, ᱢᱩᱞᱭᱟᱝᱠᱚᱱ, ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱥᱚᱱ ᱟᱨ ᱯᱩᱨᱟᱹ ᱵᱤᱵᱨᱚᱬ᱾",
    mobileFirst:"ᱢᱚᱵᱟᱭᱤᱞ ᱢᱩᱫᱽ",
    mobileFirstDesc:"ᱠᱚᱢ ᱫᱟᱢ ᱟᱱᱰᱨᱚᱭᱤᱰ ᱥᱢᱟᱨᱴᱯᱷᱚᱱ ᱞᱟᱹᱜᱤᱫ ᱛᱮᱭᱟᱨ ᱠᱟᱱ ᱤᱱᱴᱟᱨᱯᱷᱮᱥ᱾",
    practicalTraining:"ᱢᱩᱬᱩᱛ ᱦᱟᱡᱟᱨᱰ ᱞᱟᱹᱜᱤᱫ ᱠᱟᱹᱢᱤ ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ", howItWorks:"ᱚᱱᱟ ᱪᱮᱞᱠᱟ ᱠᱟᱹᱢᱤᱭᱟ",
    verifiedJourney:"ᱥᱤᱠᱷᱟᱹ ᱠᱷᱚᱱ ᱵᱤᱥᱣᱟᱥᱡᱚᱜ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱥᱚᱱ ᱫᱷᱟᱹᱵᱤᱡ", learn:"ᱥᱤᱠᱷᱟᱹ",
    learnDesc:"ᱧᱮᱞᱚᱜ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱥᱟᱢᱟᱜᱨᱤ ᱯᱟᱲᱦᱟᱣ", practise:"ᱥᱤᱠᱟᱹᱣ",
    practiseDesc:"ᱤᱱᱴᱟᱨᱮᱠᱴᱤᱵ ᱥᱤᱠᱟᱹᱣ ᱯᱩᱨᱟᱹ ᱢᱮ", assess:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ",
    assessDesc:"ᱢᱚᱰᱭᱩᱞ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱨᱮ ᱡᱚᱵᱟᱵ ᱮᱢ ᱢᱮ", certify:"ᱥᱟᱨᱴᱤᱯᱷᱟᱭ",
    certifyDesc:"QR ᱥᱟᱶ ᱵᱤᱥᱣᱟᱥ ᱦᱚᱪᱚᱜ ᱨᱮᱠᱚᱨᱰ ᱧᱟᱢ ᱢᱮ", saferWorkforce:"ᱟᱨᱦᱚᱸ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱟᱨ ᱛᱮᱭᱟᱨ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱫᱚᱞ ᱵᱮᱱᱟᱣ ᱢᱮ᱾",
    connectedPlatform:"ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ, ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱟᱨ ᱠᱚᱢᱯᱞᱟᱭᱮᱱᱥ ᱢᱤᱫ ᱥᱟᱦᱟᱡ ᱯᱞᱮᱴᱯᱷᱚᱨᱢ ᱨᱮ ᱡᱩᱲᱟᱹᱣ ᱠᱟᱱᱟ᱾",
    accessSurakshaSetu:"ᱥᱩᱨᱚᱠᱪᱷᱟᱥᱮᱛᱩ ᱵᱮᱵᱚᱦᱟᱨ ᱢᱮ", industrialLearning:"ᱡᱷᱟᱲᱠᱷᱚᱱᱰ ᱨᱮᱭᱟᱜ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱞᱟᱹᱜᱤᱫ ᱤᱱᱰᱟᱥᱴᱨᱤᱭᱟᱞ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱥᱤᱠᱷᱟᱹ᱾",
    developedBy:"ᱛᱮᱭᱟᱨ ᱠᱚᱣᱟᱜ", problemStatement:"SIH ᱥᱚᱢᱥᱭᱟ ᱵᱤᱵᱨᱚᱬ 26041",
    journeyLearn:"ᱧᱮᱞᱚᱜ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱥᱟᱢᱟᱜᱨᱤ ᱯᱟᱲᱦᱟᱣ", journeyPractise:"ᱤᱱᱴᱟᱨᱮᱠᱴᱤᱵ ᱥᱤᱠᱟᱹᱣ ᱯᱩᱨᱟᱹ ᱢᱮ",
    journeyAssess:"ᱢᱚᱰᱭᱩᱞ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱨᱮ ᱡᱚᱵᱟᱵ ᱮᱢ ᱢᱮ", journeyCertify:"QR ᱥᱟᱶ ᱵᱤᱥᱣᱟᱥ ᱦᱚᱪᱚᱜ ᱨᱮᱠᱚᱨᱰ ᱧᱟᱢ ᱢᱮ",
    backToHome:"ᱚᱲᱟᱜ ᱨᱮ ᱨᱩᱣᱟᱹᱲ", welcomeBack:"ᱫᱚᱦᱲᱟ ᱡᱚᱦᱟᱨ", createAccount:"ᱟᱢᱟᱜ ᱠᱷᱟᱛᱟ ᱵᱮᱱᱟᱣ ᱢᱮ",
    signInContinue:"ᱞᱟᱦᱟᱜ ᱞᱟᱹᱜᱤᱫ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱥᱟᱶ ᱞᱚᱜᱤᱱ ᱢᱮ᱾",
    chooseRole:"ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ ᱟᱨ ᱪᱤᱱᱦᱟᱹᱯ ᱵᱤᱵᱨᱚᱬ ᱮᱢ ᱢᱮ᱾",
    worker:"ᱠᱟᱹᱢᱤᱭᱟᱹ", administrator:"ᱮᱰᱢᱤᱱᱤᱥᱴᱨᱮᱴᱚᱨ", fullName:"ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ",
    workerId:"ᱠᱟᱹᱢᱤᱭᱟᱹ ID", adminId:"ᱮᱰᱢᱤᱱ ID", sector:"ᱵᱤᱥᱚᱭ", mining:"ᱢᱟᱭᱤᱱᱤᱝ",
    steel:"ᱤᱥᱯᱟᱛ", manufacturing:"ᱢᱮᱱᱩᱯᱷᱮᱠᱪᱟᱨᱤᱝ", micaProcessing:"ᱢᱟᱭᱠᱟ ᱯᱨᱚᱥᱮᱥᱤᱝ",
    contractWork:"ᱴᱷᱤᱠᱟ ᱠᱟᱹᱢᱤ", other:"ᱮᱴᱟᱜ", email:"ᱤᱢᱮᱞ", password:"ᱯᱟᱥᱣᱟᱨᱰ",
    pleaseWait:"ᱫᱚᱭᱟ ᱠᱟᱛᱮ ᱛᱟᱹᱝᱜᱤ ᱢᱮ...", newToApp:"ᱥᱩᱨᱚᱠᱪᱷᱟᱥᱮᱛᱩ ᱨᱮ ᱱᱟᱶᱟᱱᱤᱭᱟᱹ?",
    alreadyRegistered:"ᱞᱮᱠᱟᱱ ᱨᱮᱡᱤᱥᱴᱟᱨ ᱟᱠᱟᱱᱟ?", backendNotConfigured:"ᱵᱮᱠᱮᱱᱰ ᱥᱮᱴ ᱵᱟᱝ ᱦᱚᱪᱚ ᱟᱠᱟᱱᱟ᱾ .env ᱨᱮ Supabase ᱢᱟᱱ ᱮᱢ ᱢᱮ᱾",
    accountCouldNotBeCreated:"ᱠᱷᱟᱛᱟ ᱵᱮᱱᱟᱣ ᱵᱟᱝ ᱞᱮᱠᱟᱜᱼᱟ᱾", confirmEmailToLogin:"ᱠᱷᱟᱛᱟ ᱵᱮᱱᱟᱣ ᱮᱱᱟ᱾ ᱤᱢᱮᱞ ᱯᱨᱚᱢᱟᱬ ᱢᱮ, ᱛᱟᱭᱚᱢ ᱞᱚᱜᱤᱱ ᱢᱮ᱾",
    englishQuestionRequired:"English ᱨᱮ ᱠᱩᱠᱞᱤ ᱞᱟᱹᱠᱛᱤᱭᱟ᱾",
    selectedAnswerRequired:"ᱵᱟᱪᱷᱟᱣ ᱠᱟᱱ ᱴᱷᱤᱠ ᱡᱚᱵᱟᱵ ᱠᱷᱟᱹᱞᱤ ᱵᱟᱝ ᱦᱚᱪᱚ ᱞᱮᱠᱟᱜᱼᱟ᱾", authEyebrow:"ᱤᱱᱰᱟᱥᱴᱨᱤᱭᱟᱞ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱛᱮᱭᱟᱨᱤ ᱠᱷᱚᱱ ᱮᱦᱚᱵᱚᱜᱼᱟ᱾",
    questionTranslationRequired:"ᱥᱟᱵᱮ ᱢᱟᱲᱟᱝ English, Hindi ᱟᱨ Santali ᱛᱮ ᱠᱩᱠᱞᱤ ᱮᱢ ᱢᱮ᱾",
    optionsTranslationRequired:"ᱯᱩᱨᱟᱹ ᱠᱟᱱ ᱡᱚᱵᱟᱵ ᱵᱟᱪᱷᱟᱣ ᱟᱨ ᱵᱤᱵᱨᱚᱬ Hindi ᱟᱨ Santali ᱨᱮ ᱵᱚᱫᱚᱞ ᱢᱮ᱾",
    authDescription:"ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ, ᱠᱟᱹᱢᱤ ᱥᱤᱢᱩᱞᱮᱥᱚᱱ, ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱟᱨ ᱵᱤᱥᱣᱟᱥᱡᱚᱜ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱧᱟᱢ ᱢᱮ᱾",
    backToDashboard:"ᱰᱮᱥᱵᱳᱨᱰ ᱨᱮ ᱨᱩᱣᱟᱹᱲ", workerCentre:"ᱠᱟᱹᱢᱤᱭᱟᱹ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱠᱮᱱᱫᱨ", module:"ᱢᱚᱰᱭᱩᱞ", verificationQr:"ᱵᱤᱥᱣᱟᱥ QR",
    average:"ᱜᱚᱲ", performance:"ᱠᱟᱹᱢᱤ ᱧᱮᱞ", assessmentHistory:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱦᱤᱥᱴᱨᱤ",
    noCompletedAssessments:"ᱱᱤᱛ ᱫᱷᱟᱹᱵᱤᱡ ᱡᱟᱦᱟᱱ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱵᱟᱝ ᱯᱩᱨᱟᱹ ᱟᱠᱟᱱᱟ᱾",
    openModule:"ᱢᱚᱰᱭᱩᱞ ᱡᱷᱤᱡ ᱢᱮ", viewResult:"ᱨᱤᱡᱟᱞᱴ ᱧᱮᱞ", removeFromHistory:"ᱦᱤᱥᱴᱨᱤ ᱠᱷᱚᱱ ᱚᱪᱚᱜ",
    verifiedRecords:"ᱵᱤᱥᱣᱟᱥ ᱦᱚᱪᱚ ᱨᱮᱠᱚᱨᱰ", completeForCertificate:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱧᱟᱢ ᱞᱟᱹᱜᱤᱫ ᱡᱚᱜᱽᱭᱚ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱯᱩᱨᱟᱹ ᱢᱮ᱾",
    viewCertificate:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱧᱮᱞ", verified:"ᱵᱤᱥᱣᱟᱥ ᱦᱚᱪᱚ", dashboardBack:"ᱰᱮᱥᱵᱳᱨᱰ",
    safetyModule:"ᱥᱩᱨᱚᱠᱪᱷᱟ ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ ᱢᱚᱰᱭᱩᱞ", understand:"ᱵᱩᱡᱷᱟᱹᱣ", learningObjectives:"ᱥᱤᱠᱷᱟᱹ ᱩᱫᱽᱫᱮᱥᱭᱚ",
    safetyPrinciple:"ᱥᱩᱨᱚᱠᱪᱷᱟ ᱱᱤᱭᱚᱢ", remember:"ᱩᱭᱦᱟᱹᱨ ᱢᱮ", safetyPrincipleText:"ᱠᱟᱹᱢᱤ ᱢᱟᱲᱟᱝ ᱛᱷᱟᱢ ᱟᱨ ᱦᱟᱡᱟᱨᱰ ᱵᱤᱪᱷᱟᱨ ᱢᱮ᱾ ᱥᱟᱭᱤᱴ ᱱᱤᱭᱚᱢ, ᱪᱮᱛᱟᱣ ᱪᱤᱱᱦᱟᱹ, ᱟᱹᱫᱮᱥ ᱟᱱᱩᱥᱟᱨ ᱤᱥᱚᱞᱮᱥᱚᱱ, ᱞᱟᱹᱠᱛᱤ PPE ᱟᱨ ᱟᱯᱟᱛᱠᱟᱞᱤᱱ ᱱᱤᱨᱫᱮᱥ ᱢᱟᱱ ᱢᱮ᱾ ᱥᱤᱠᱷᱟᱹ ᱯᱩᱨᱟᱹ ᱞᱟᱹᱜᱤᱫ ᱦᱚᱸ ᱦᱟᱡᱟᱨᱰ ᱴᱷᱟᱶ ᱨᱮ ᱟᱞᱚᱢ ᱥᱮᱱᱚᱜᱼᱟ᱾", practical:"ᱤᱱᱴᱟᱨᱮᱠᱴᱤᱵ ᱠᱟᱹᱢᱤ ᱥᱤᱠᱟᱹᱣ",
    cameraExercise:"ᱠᱮᱢᱨᱟ ᱥᱟᱶ ᱦᱟᱡᱟᱨᱰ ᱥᱤᱠᱟᱹᱣ", startAssessment:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱮᱦᱚᱵ",
    completeModuleTest:"ᱢᱚᱰᱭᱩᱞ ᱴᱮᱥᱴ ᱯᱩᱨᱟᱹ ᱢᱮ",
    completeAllQuestions:"ᱡᱚᱢᱟ ᱢᱟᱲᱟᱝ ᱥᱟᱱᱟᱢ ᱠᱩᱠᱞᱤ ᱨᱮ ᱡᱚᱵᱟᱵ ᱮᱢ ᱢᱮ᱾",
    assessmentSwitchWarning:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱚᱠᱛᱚ ᱴᱮᱵ ᱟᱨ ᱮᱯ ᱵᱚᱫᱚᱞᱚᱜ ᱨᱮ ᱱᱚᱣᱟ ᱯᱨᱚᱭᱟᱥ ᱵᱟᱹᱛᱤᱞ ᱦᱚᱪᱚᱜᱼᱟ ᱟᱨ ᱡᱚᱢᱟ ᱵᱟᱝ ᱦᱚᱪᱚᱜᱼᱟ᱾",
    noQuestionsConfigured:"ᱱᱚᱣᱟ ᱢᱚᱰᱭᱩᱞ ᱞᱟᱹᱜᱤᱫ ᱱᱤᱛ ᱡᱟᱦᱟᱱ ᱠᱩᱠᱞᱤ ᱥᱮᱴ ᱵᱟᱝ ᱦᱚᱪᱚ ᱟᱠᱟᱱᱟ᱾",
    translationsIncomplete:"ᱱᱚᱣᱟ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱵᱟᱝ ᱧᱟᱢᱚᱜᱼᱟ ᱪᱮᱫᱟᱜ ᱢᱤᱫ ᱥᱮ ᱟᱹᱰᱤ ᱠᱩᱠᱞᱤ ᱨᱮ English, Hindi ᱥᱮ Santali ᱵᱚᱫᱚᱞ ᱵᱟᱹᱝ ᱯᱩᱨᱟᱹᱭᱟ᱾ Admin ᱥᱟᱶ ᱡᱚᱯᱚᱲ ᱢᱮ᱾",
    translationUnavailable:"ᱵᱚᱫᱚᱞ ᱵᱟᱹᱝ ᱧᱟᱢᱚᱜᱼᱟ",
    attemptInterrupted:"ᱯᱨᱚᱭᱟᱥ ᱛᱷᱟᱢ ᱮᱱᱟ", attemptNotSubmitted:"ᱱᱚᱣᱟ ᱯᱨᱚᱭᱟᱥ ᱡᱚᱢᱟ ᱵᱟᱝ ᱦᱚᱪᱚ ᱮᱱᱟ᱾ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱫᱚᱦᱲᱟ ᱮᱦᱚᱵ ᱢᱮ᱾",
    restartAssessment:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱫᱚᱦᱲᱟ ᱮᱦᱚᱵ", activeAssessment:"ᱮᱦᱚᱵ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ", question:"ᱠᱩᱠᱞᱤ",
    answered:"ᱡᱚᱵᱟᱵ ᱮᱢ ᱟᱠᱟᱱ", of:"ᱠᱷᱚᱱ", submitting:"ᱡᱚᱢᱟ ᱦᱚᱭᱚᱜ...", submitAssessment:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱡᱚᱢᱟ",
    assessmentResult:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱨᱤᱡᱟᱞᱴ", assessmentCompleted:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱯᱩᱨᱟᱹ ᱮᱱᱟ",
    reviewAndRetry:"ᱢᱚᱰᱭᱩᱞ ᱧᱮᱞ ᱟᱨ ᱫᱚᱦᱲᱟ ᱠᱩᱥᱤᱥ ᱢᱮ", generateCertificate:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱵᱮᱱᱟᱣ",
    answerReview:"ᱡᱚᱵᱟᱵ ᱧᱮᱞ", correctAnswers:"ᱴᱷᱤᱠ ᱡᱚᱵᱟᱵ", yourAnswer:"ᱟᱢᱟᱜ ᱡᱚᱵᱟᱵ:", correctAnswer:"ᱴᱷᱤᱠ ᱡᱚᱵᱟᱵ:",
    correct:"ᱴᱷᱤᱠ", incorrect:"ᱵᱷᱩᱞ", certificateReady:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱛᱮᱭᱟᱨ",
    generating:"ᱵᱮᱱᱟᱣ ᱦᱚᱭᱚᱜ...", congratulations:"ᱡᱚᱦᱟᱨ ᱟᱨ ᱵᱟᱹᱲᱟᱭ",
    certificateOfCompletion:"ᱯᱩᱨᱟᱹ ᱦᱚᱪᱚ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ", awardedTo:"ᱱᱚᱣᱟ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱜᱚᱨᱵ ᱥᱟᱶ ᱮᱢ ᱟᱠᱟᱱᱟ",
    score:"ᱥᱠᱳᱨ", certificateId:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ID", issued:"ᱮᱢ ᱟᱠᱟᱱ", scanToVerify:"ᱱᱚᱣᱟ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱵᱤᱥᱣᱟᱥ ᱞᱟᱹᱜᱤᱫ QR ᱥᱠᱮᱱ ᱢᱮ᱾",
    downloadPdf:"PDF ᱰᱟᱣᱱᱞᱳᱰ", certificateVerification:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱵᱤᱥᱣᱟᱥ",
    enterCertificateId:"ᱵᱤᱥᱮᱥ ᱥᱩᱨᱚᱠᱪᱷᱟᱥᱮᱛᱩ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ID ᱮᱢ ᱢᱮ᱾", checking:"ᱧᱮᱞ ᱦᱚᱭᱚᱜ...",
    verifyAction:"ᱵᱤᱥᱣᱟᱥ ᱢᱮ", certificateVerified:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱵᱤᱥᱣᱟᱥ ᱮᱱᱟ", authenticRecord:"ᱥᱩᱨᱚᱠᱪᱷᱟᱥᱮᱛᱩ ᱨᱮᱭᱟᱜ ᱥᱟᱹᱨᱤ ᱨᱮᱠᱚᱨᱰ",
    certificateRevoked:"ᱱᱚᱣᱟ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱨᱟᱹᱫ ᱮᱱᱟ ᱟᱨ ᱱᱤᱛ ᱵᱟᱝ ᱵᱤᱥᱣᱟᱥᱡᱚᱜ᱾", certificateNotFound:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱵᱟᱝ ᱧᱟᱢ ᱮᱱᱟ᱾",
    workerManagement:"ᱠᱟᱹᱢᱤᱭᱟᱹ ᱢᱮᱱᱮᱡᱽ", registeredWorkerDesc:"ᱨᱮᱡᱤᱥᱴᱟᱨ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱟᱨ ᱠᱷᱟᱛᱟ ᱥᱴᱮᱴᱚᱥ ᱧᱮᱞ ᱟᱨ ᱢᱮᱱᱮᱡᱽ᱾",
    searchWorker:"ᱧᱩᱛᱩᱢ, Worker ID ᱟᱨ ᱥᱮᱠᱴᱚᱨ ᱥᱮᱸᱫᱽᱨᱟ...", name:"ᱧᱩᱛᱩᱢ", status:"ᱥᱴᱮᱴᱚᱥ", joined:"ᱡᱩᱲᱟᱹᱣ ᱮᱱᱟ", actions:"ᱠᱟᱹᱢᱤ",
    active:"ᱠᱟᱹᱢᱤᱭᱟᱹ", inactive:"ᱵᱟᱝ ᱠᱟᱹᱢᱤᱭᱟᱹ", activate:"ᱪᱟᱹᱞᱩ ᱢᱮ", deactivate:"ᱵᱚᱸᱫ ᱢᱮ", remove:"ᱚᱪᱚᱜ",
    noWorkersFound:"ᱡᱟᱦᱟᱱ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱵᱟᱝ ᱧᱟᱢ ᱮᱱᱟ᱾", moduleNotFound:"ᱢᱚᱰᱭᱩᱞ ᱵᱟᱝ ᱧᱟᱢ ᱮᱱᱟ᱾",
    questionsFound:"ᱡᱟᱦᱟᱱ ᱠᱩᱠᱞᱤ ᱵᱟᱝ ᱧᱟᱢ ᱮᱱᱟ᱾", noAssessments:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱨᱮᱠᱚᱨᱰ ᱵᱟᱝ ᱢᱮᱱᱟᱜᱼᱟ᱾", noCertificates:"ᱢᱤᱞᱟᱜ ᱠᱟᱱ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱵᱟᱝ ᱧᱟᱢ ᱮᱱᱟ᱾",
    removeAssessmentConfirm:"ᱱᱚᱣᱟ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱟᱢᱟᱜ ᱦᱤᱥᱴᱨᱤ ᱠᱷᱚᱱ ᱚᱪᱚᱜ ᱢᱮ?", removeCertificateConfirm:"ᱱᱚᱣᱟ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱦᱤᱥᱴᱨᱤ ᱠᱷᱚᱱ ᱚᱪᱚᱜ ᱢᱮ? ᱢᱩᱞ ᱵᱤᱥᱣᱟᱥ ᱨᱮᱠᱚᱨᱰ ᱵᱟᱹᱛᱤᱞ ᱵᱟᱝ ᱦᱚᱭᱚᱜᱼᱟ᱾",
    couldNotRemoveAssessment:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱚᱪᱚᱜ ᱵᱟᱝ ᱞᱮᱠᱟᱜᱼᱟ:", couldNotRemoveCertificate:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱚᱪᱚᱜ ᱵᱟᱝ ᱞᱮᱠᱟᱜᱼᱟ:",
    workforce:"ᱠᱟᱹᱢᱤ ᱫᱚᱞ", trainingContent:"ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ ᱥᱟᱢᱟᱜᱨᱤ", manageModuleDescription:"ᱢᱚᱬᱮ ᱥᱩᱨᱚᱠᱪᱷᱟ ᱵᱤᱥᱚᱭ ᱥᱟᱶ ᱡᱩᱲᱟᱹᱣ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱥᱟᱢᱟᱜᱨᱤ ᱢᱮᱱᱮᱡᱽ ᱢᱮ᱾", assessmentEngine:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱥᱤᱥᱴᱚᱢ",
    addQuestion:"ᱠᱩᱠᱞᱤ ᱥᱮᱞᱮᱫ", editQuestion:"ᱠᱩᱠᱞᱤ ᱥᱚᱢᱯᱟᱫᱚᱱ", questionEditor:"ᱠᱩᱠᱞᱤ ᱮᱰᱤᱴᱚᱨ", questionManager:"ᱠᱩᱠᱞᱤ ᱢᱮᱱᱮᱡᱚᱨ", questionManagerDescription:"ᱵᱟᱦᱨᱮ ᱯᱟᱹᱨᱥᱤ ᱨᱮ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱠᱩᱠᱞᱤ ᱵᱮᱱᱟᱣ, ᱥᱚᱢᱯᱟᱫᱚᱱ ᱟᱨ ᱰᱤᱞᱤᱴ ᱢᱮ᱾",
    manageQuestions:"ᱠᱩᱠᱞᱤ ᱢᱮᱱᱮᱡᱽ", searchQuestions:"ᱠᱩᱠᱞᱤ ᱥᱮᱸᱫᱽᱨᱟ...", allModules:"ᱥᱟᱱᱟᱢ ᱢᱚᱰᱭᱩᱞ",
    questionType:"ᱠᱩᱠᱞᱤ ᱨᱮᱭᱟᱜ ᱞᱮᱠᱟ", sortOrder:"ᱥᱟᱡᱟᱣ ᱠᱚᱨᱚᱢ", imageOptional:"ᱪᱤᱛᱟᱹᱨ URL (ᱵᱟᱝ ᱞᱟᱹᱠᱛᱤ)",
    explanation:"ᱵᱤᱵᱨᱚᱬ", delete:"ᱰᱤᱞᱤᱴ", save:"ᱥᱟᱵᱮ", modulePerformance:"ᱢᱚᱰᱭᱩᱞ ᱠᱟᱹᱢᱤ",
    originalCertificateRecord:"ᱢᱩᱞ ᱮᱢ ᱠᱟᱱ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱨᱮᱠᱚᱨᱰ᱾", completed:"ᱯᱩᱨᱟᱹ", moduleAssessments:"ᱢᱚᱰᱭᱩᱞ ᱟᱱᱩᱥᱟᱨ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ", complianceDescription:"ᱯᱞᱮᱴᱯᱷᱚᱨᱢ ᱨᱮᱭᱟᱜ ᱯᱨᱚᱥᱤᱠᱠᱷᱚᱱ ᱟᱨ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱥᱚᱱ ᱠᱟᱹᱢᱤ᱾",
    totalWorkers:"ᱢᱚᱴ ᱠᱟᱹᱢᱤᱭᱟᱹ", averageScore:"ᱜᱚᱲ ᱥᱠᱳᱨ", safetyCompliance:"ᱥᱩᱨᱚᱠᱪᱷᱟ ᱠᱚᱢᱯᱞᱟᱭᱮᱱᱥ ᱥᱟᱨᱟᱢᱥᱚ",
    issuedCertificates:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱠᱮᱱᱫᱨ", searchCertificates:"ᱠᱟᱹᱢᱤᱭᱟᱹ ᱧᱩᱛᱩᱢ / ID / ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ID ᱥᱮᱸᱫᱽᱨᱟ...",
    certificateCount:"ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱧᱟᱢ", oneCertificateFound:"ᱢᱤᱫ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱧᱟᱢ", revoked:"ᱨᱟᱹᱫ", revoke:"ᱨᱟᱹᱫ ᱢᱮ", view:"ᱧᱮᱞ",
    assessmentRecords:"ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱨᱮᱠᱚᱨᱰ", workerHistoryAdminNote:"ᱠᱟᱹᱢᱤᱭᱟᱹ ᱦᱤᱥᱴᱨᱤ ᱠᱷᱚᱱ ᱚᱪᱚᱜ ᱦᱚᱪᱚᱜ ᱱᱚᱣᱟ ᱠᱚᱢᱯᱞᱟᱭᱮᱱᱥ ᱨᱮᱠᱚᱨᱰ ᱚᱪᱚᱜ ᱵᱟᱝ ᱦᱚᱭᱟ᱾", liveActivity:"ᱞᱟᱭᱤᱵ ᱠᱟᱹᱢᱤ", recentAssessments:"ᱱᱟᱶᱟ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ",
    noAssessmentsYet:"ᱱᱤᱛ ᱫᱷᱟᱹᱵᱤᱡ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱵᱟᱝ ᱢᱮᱱᱟᱜᱼᱟ᱾", date:"ᱢᱟᱹᱦᱤᱛ", percentage:"ᱯᱨᱚᱛᱤᱥᱚᱛ", submitted:"ᱡᱚᱢᱟ ᱦᱚᱪᱚ",
    questionDeleteConfirm:"ᱱᱚᱣᱟ ᱠᱩᱠᱞᱤ ᱰᱤᱞᱤᱴ ᱢᱮ?", assessmentDeleteConfirm:"ᱱᱚᱣᱟ ᱢᱩᱞᱭᱟᱝᱠᱚᱱ Admin ᱨᱮᱠᱚᱨᱰ ᱠᱷᱚᱱ ᱚᱪᱚᱜ ᱢᱮ?",
    certificateRevokeConfirm:"ᱱᱚᱣᱟ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱨᱟᱹᱫ ᱢᱮ?", workerRemoveConfirm:"ᱱᱚᱣᱟ ᱠᱟᱹᱢᱤᱭᱟᱹ Admin ᱛᱟᱞᱠᱟ ᱠᱷᱚᱱ ᱚᱪᱚᱜ ᱢᱮ? ᱢᱩᱞᱭᱟᱝᱠᱚᱱ ᱟᱨ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ ᱨᱮᱠᱚᱨᱰ ᱢᱮᱱᱟᱜ ᱛᱟᱦᱮᱱᱟ᱾"
  }
};

export function AppProvider({children}) {
  const [lang,setLang] = useState(localStorage.getItem("ss-lang") || "en");
  const [theme,setTheme] = useState(localStorage.getItem("ss-theme") || "light");
  const [session,setSession] = useState(null);
  const [profile,setProfile] = useState(null);

  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    localStorage.setItem("ss-theme",theme);
  },[theme]);

  useEffect(() => {
    document.documentElement.lang = lang === "sat" ? "sat-IN" : `${lang}-IN`;
    localStorage.setItem("ss-lang",lang);
  },[lang]);

  useEffect(() => {
    if (!supabase) return;

    supabase.auth.getSession().then(({data}) => setSession(data.session));

    const {data:{subscription}} =
      supabase.auth.onAuthStateChange((_e,s) => setSession(s));

    return () => subscription.unsubscribe();
  },[]);

  useEffect(() => {
    if (!session || !supabase) {
      setProfile(null);
      return;
    }

    supabase.from("profiles")
      .select("*")
      .eq("id",session.user.id)
      .single()
      .then(({data}) => setProfile(data));
  },[session]);

  const t = key => text[lang]?.[key] || text.en[key] || key;
  const locale = lang === "sat" ? "sat-IN" : lang === "hi" ? "hi-IN" : "en-IN";
  const formatDate = value => new Date(value).toLocaleDateString(locale);
  const formatDateTime = value => new Date(value).toLocaleString(locale);

  const value = useMemo(() => ({
    lang,setLang,theme,setTheme,session,profile,setProfile,t,formatDate,formatDateTime
  }),[lang,theme,session,profile]);

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export const useApp = () => useContext(AppContext);